# .github/workflows/ci.yml
name: AutoSec CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        working-directory: backend  # ✅ Moved here

      - name: Run backend lint
        run: python -m compileall .
        working-directory: backend  # ✅ Moved here

  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install
        working-directory: frontend  # ✅ Moved here

      - name: Run build
        run: npm run build
        working-directory: frontend  # ✅ Moved here
